### ISSUE TITLE
Support CSS Class Styling

### ISSUE THREAD

**Issue by kyleherzog** [wbaldoumas/markdown-colorcode#100]
## Problem Statement

I need to be able to format HTML via CSS class names instead of inline style attributes.

## Proposed Solution

ColorCode supports doing this using the HtmlClassFormatter instead of the HtmlFormatter.  Having the ability to select this option would be big improvement. This could be via a parameter on the UseColorCode method or just a separate Use method altogether.

**Comment by wbaldoumas** [comment]
@kyleherzog thanks for the interest in improving Markdown.ColorCode!

If this is something you'd be interested in contributing yourself, feel free to take a stab at this. If not, I will find some time to work it in later.

**Comment by wbaldoumas** [comment]
@kyleherzog I've published a `1.1.0-preview-1` preview version that introduces the ability to use CSS class-based styling. Give it a go and let me know if this meets your needs.

**Comment by kyleherzog** [comment]
Looks really good in my testing.  Thanks!

**Comment by wbaldoumas** [comment]
This should be all set. I've also included multi-targeting support for .NET 7, which you may benefit from as well. Please use the latest v1.1.1 version of this package and feel free to open a new issue if anything else comes up. 

Thanks for the contribution!

**Comment by kostas-baltsoft** [comment]
Where can I find the default CSS template for ```HtmlFormatterType.Css``` rendering?
