### ISSUE TITLE
support netstandard 2.0

### ISSUE THREAD

**Issue by ElderJames** [wbaldoumas/markdown-colorcode#149]
I want to use markdig and this extensions in Source Generators.

**Comment by wbaldoumas** [comment]
Thanks for opening up this issue, @ElderJames. 

Unfortunately [CsharpToColouredHTML](https://github.com/Swiftly1/CsharpToColouredHTML), which this library depends on, does not support .NET Standard 2.0. Support for .NET Standard 2.0 will need to be added there first before making these updates to Markdown.ColorCode.

**Comment by wbaldoumas** [comment]
@ElderJames unfortunately the pull request that was just merged won't allow for the `Markdown.ColorCode.CSharpToColoredHtml` package to be built. 

Although you only targeted `Markdown.ColorCode` with your .NET Standard 2.0 TFM update, `Markdown.ColorCode.CSharpToColoredHtml` depends on the main package and will not build with that update in place. For now, I'm reopening this issue and reverting your change. 

Please open an issue in the [CsharpToColouredHTML](https://github.com/Swiftly1/CsharpToColouredHTML) repository regarding .NET Standard 2.0 support so we can get this change pushed through for both `Markdown.ColorCode` and `Markdown.ColorCode.CSharpToColoredHtml` if you still need it.

**Comment by ElderJames** [comment]
What's the issue with `Markdown.ColorCode.CSharpToColoredHtml`? It build successfully on my locale PC.

**Comment by wbaldoumas** [comment]
> What's the issue with `Markdown.ColorCode.CSharpToColoredHtml`? It build successfully on my locale PC.

You're right. I opened https://github.com/wbaldoumas/markdown-colorcode/pull/152 to reintroduce your changes but also bump the version number to trigger a release. Thanks for the patience on this one - totally my bad regarding the build issue. 🤦‍♀️
