### ISSUE TITLE
Method of eliminating background color?

### ISSUE THREAD

**Issue by Nyazira** [wbaldoumas/markdown-colorcode#163]
When I specify a specific language, the `<pre>` is nested in a layer of `<div>`:
```
<div style="color:#DADADA;background-color:#1E1E1E;">
```
That's something I don't want, because it makes the background of my code block look weird with black stuff all around it.
Is there any way to get rid of that effect?

![2024-09-23_23-42-52](https://github.com/user-attachments/assets/4e3b9bc1-6596-4f4f-91eb-69221814ec82)

**Comment by wbaldoumas** [comment]
A few things here that would help:

- Which version of the package are you currently on, and which package (there are two hosted in this repo)?
- Could you zip and upload a simple reproduction sample?

Once I have that info on hand I can take a closer look and see if it's something I can easily change, or if it's an underlying issue with [ColorCode-Universal](https://github.com/CommunityToolkit/ColorCode-Universal) or [CsharpToColouredHTMLl](https://github.com/Swiftly1/CsharpToColouredHTML).

As a side note, if you're mostly using this to add syntax highlighting for C# code, I definitely recommend using `Markdown.ColorCode.CSharpToColoredHtml`, as it provides improved syntax highlighting for C# code. Read more on that [here](https://github.com/wbaldoumas/markdown-colorcode?tab=readme-ov-file#improved-c-syntax-highlighting).

**Comment by Nyazira** [comment]
Thank you for replying.
package:
```
<PackageReference Include="Markdig" Version="0.37.0" />
<PackageReference Include="Markdown.ColorCode" Version="2.3.0" />
```
and I use css file "github-markdown.css"
[markdown-colorcode-simple.zip](https://github.com/user-attachments/files/17174797/markdown-colorcode-simple.zip)

**Comment by Nyazira** [comment]
Thank you so much, I basically solved the problem.
