### ISSUE TITLE
compatibility issue

### ISSUE THREAD

**Issue by sina33** [wbaldoumas/markdown-colorcode#35]
## Description

Install-Package : Could not install package 'Markdown.ColorCode 1.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but 
the package does not contain any assembly references or content files that are compatible with that framework.

**Comment by wbaldoumas** [comment]
@sina33 this project only supports .NET 6.0 at the moment. If you'd like to add support for .NET Framework by targeting .NET Standard 2.1, feel free to open up a pull request that introduces that via [multi-targeting](https://docs.microsoft.com/en-us/nuget/create-packages/multiple-target-frameworks-project-file). 👍🏻
