### ISSUE TITLE
Python is broken in the current Nuget version 

### ISSUE THREAD

**Issue by netclectic** [wbaldoumas/markdown-colorcode#72]
## Description

Python is broken in the current Nuget version : v1.0.1

It seems the last version (v2.0.13) of ColorCode had some build issue that somehow broke support for Python, it was fixed in the latest version (v2.0.14). This has been updated and merged already but the Nuget package has not been updated.

## Expected Behaviour

Python language blocks should be properly color coded

```
<div style="color:#DADADA;background-color:#1E1E1E;"><pre>
    this = that
    DoSomething()
    <span style="color:#57A64A;"># this is a comment</span>
</pre></div>
```

## Actual Behaviour

Python language blocks are not properly color coded

```
<pre><code class="language-python">    this = that
    DoSomething()
    # this is a comment
</code></pre>
```

## Affected Version

v1.0.1

## Steps to Reproduce

`dotnet add package Markdown.ColorCode --version 1.0.1`

```
string code = @"```python
    this = that
    DoSomething()
    # this is a comment
```";
                var pipeline = new MarkdownPipelineBuilder()
                    .UseAdvancedExtensions()
                    .UseColorCode()
                    .Build();
                Console.WriteLine(Markdig.Markdown.ToHtml(code, pipeline));
```

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/wbaldoumas/markdown-colorcode/blob/main/CONTRIBUTING.md)
- [x] I have verified this does not duplicate an existing issue

**Comment by wbaldoumas** [comment]
Hey, thanks for the report @netclectic! 

I just cut a new v1.0.2 release that includes the updated ColorCode packages. Let me know if this addresses the issues with Python that you were seeing and close out this issue if it is resolved. 👍🏻

**Comment by netclectic** [comment]
Yep, sorted now.

Thanks.
